strawberry_price = float(input())
banana_kg = float(input())
oranges_kg = float(input())
berries_kg = float(input())
strawberry_kg = float(input())
berries_price = float(strawberry_price / 2)
a = float( berries_price * 0.8)
banana_price = float(berries_price - a)
oranges_price = float( berries_price - (0.4 * berries_price))
total_money_needed = float((strawberry_kg * strawberry_price) + (berries_kg * berries_price) + (banana_kg * banana_price) + (oranges_kg * oranges_price))
print(total_money_needed)